
import { CircleOff  } from 'lucide-react'
import React from 'react'

type Props = {}

function NotFound({}: Props) {
  return (
    <div className='flex flex-col min-h-[70vh] w-full justify-center items-center gap-12'>
        <div className='flex flex-col items-center justify-center text-center'>
            <CircleOff size={58}/>
            <p className='text-3xl font-semibold '>
                Nothing to see here
            </p> 
            <p className='text-base font-normal'>
                So here is a random image generated by 
                <span className='text-orange-400'> Creative AI</span>
            </p>
        </div>
    </div>
  )
}

export default NotFound